gitconfig `contains-tag`

diff --git a/gitconfig b/gitconfig
--- a/gitconfig
+++ b/gitconfig
@@ -1,13 +1,16 @@
 [alias]
 	prettylog = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative
 	default = !git checkout $(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
-	contains = "! f() { \
-		sha_1=$(git show-ref refs/tags/$1 -s | head -n1); \
-		git branch --contains $sha_1 -a | rg -e \"(/release/|main)\"; \
-    }; f"
-	e = "! f() { \
-	  echo $1; \
-	}; f"
+	contains-tag = "!f() { \
+			echo \"🔎 Getting SHA for $1\"; \
+  			sha_1=$(git show-ref refs/tags/$1 -s | head -n1); \
+	  		[[ ! -z $sha_1 ]] \
+			  && { echo \"👇 Refs that contain ${sha_1:0:8}\"; } \
+			  || { echo \"❌ Not Found\"; exit 1; } \
+			; \
+  			git branch --contains $sha_1 -a; \
+    	}; f"
+
 
 [color]
 	ui = true
